#DATABASE CONFIGURATION
spring:
  datasource:
    url: jdbc:h2:file:~/exam2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  data:
    elasticsearch:
      cluster-nodes: localhost:9300

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

url:
  movieDb: https://api.themoviedb.org/3


movie:
  api:
    key: a5719ed0a0498b8e7389f828419d49b2

logging:
  level:
    org.hibernate.jpa: DEBUG
    org.hibernate.SQL: DEBUG