#DATABASE CONFIGURATION
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie?serverTimezone=Europe/Warsaw&useSSL=False
    username: root
    password: "@EvilCorp123!"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    elasticsearch:
      cluster-nodes: localhost:9300

url:
  movieDb: https://api.themoviedb.org/3


movie:
  api:
    key: "a5719ed0a0498b8e7389f828419d49b2"

